export interface ModalProps {
    prefixCls?: string,
    className?: string,
    activeClassName?: string,
    maskTransitionName?: string,
    transitionName?: string,
    title?: string,
    inline?: boolean,
    full?: boolean,
    disabled?: boolean,
    noBorder?: boolean,
    visible: boolean,
    closable?: boolean,
    ghost?: boolean,
    transparent?: boolean,
    maskClose?: boolean,
    closeCallback?: any,
    onClick?: any,
    lang?: 'cn' | 'hk' | 'en'
    buttons?: Array<any>,
    buttonDirection?: 'horizontally' | 'vertical',
    style?: React.CSSProperties,
    maskStyle?: React.CSSProperties,
    footer?: JSX.Element,
}